//: [Previous](@previous)

import Foundation

let input = """
ivyhczwokexltwhsfamqprbnuy
ivjhcjdokexltwwsfamqpabnuy
ivjhczdokebltwgsfydqprbnuy
ivjhcadokexftogsfamqprbnuy
idjhczdokexltwgsfacqprbnuh
ivjhgzookexltwgsfamqjrbnuy
uvjhctdokexltwosfamqprbnuy
ivrhczdokexltwhzfamqprbnuy
ivjhczuxkexltwgsfamqprbney
ivjhczdokemltwgsfadnprbnuy
ifjhczdokexltwgsfamqprbkuf
ivjhkzdokltltwgsfamqprbnuy
ivjuczdhkexltwgsfamqprtnuy
ivjhjzdxkexltwgsfapqprbnuy
ivlhczdoxexltwgsfamqprgnuy
ivjhczdoknxltwgssamqsrbnuy
ivjhczdokexltwgswadqprbruy
ivjhczdokexthwgsfampprbnuy
uvjhczrozexltwgsfamqprbnuy
ivolczdokexltwgsffmqprbnuy
ivjhczibkexltwgsfamoprbnuy
ivjhczdokefltmgsfamqprbouy
ivjhczdobexltngsfamsprbnuy
ivjhczdokexltwvsfxqqprbnuy
dvjhczdokexucwgsfamqprbnuy
kvjhszkokexltwgsfamqprbnuy
ivjhczdokexrtegsfamqprbnus
ivjhctdokexltwglgamqprbnuy
ivjhczdozexutwgsfamqdrbnuy
ivjhczqokemltwgsfakqprbnuy
uvjhczdokexlqwgsfadqprbnuy
ivjhczdohexltwglffmqprbnuy
izjhczdokexltwgsfamqprbsqy
iajhczdokwxltwgjfamqprbnuy
ivjfczdokexllwgslamqprbnuy
ivjhczdoyexltwgsfamqdrbnxy
ivjhczdokekwtwssfamqprbnuy
ivjhcodokexltwgsfamqirxnuy
ihjhhzdokexltwgsfamqlrbnuy
ivjdpzdokexltwfsfamqprbnuy
ivjhcpdokexltwgsfamqqrbruy
qvjhcziokexltwgsfamqprbnny
ivohczdomexltwgsfkmqprbnuy
ivjhczhokhxlywgsfamqprbnuy
ivjhczdokexltwgmffmqprbruy
ivjhczdokqxltwgcfamqprbnyy
ivjhczdokepltwgsfamcprbnay
ivjhczdokexltwgseamqpmbnua
ivjzczdokexltwgszamqplbnuy
ivjhczpokexltwgvfgmqprbnuy
idjhczdokexltwgsxamqprbndy
ivjhczdxkexltwgcgamqprbnuy
ivjhczdckexatpgsfamqprbnuy
ivjrczdorexltwgsfamqprbnvy
ivjoczdokexltwgswamqprbtuy
iylhczdokexltwgsfamqpxbnuy
imxhczdokkxltwgsfamqprbnuy
ivvhczdoktxltwgsfamaprbnuy
ivyhczdokexltwhsfayqprbnuy
ivjhcrdokexltegsfamqprbnum
rvjhezdokexltwgsoamqprbnuy
ivjzczdokexlbwgsfkmqprbnuy
ivjhczdokelltwgsyamqprbnoy
ixjhczdorexltwgsfamqprbuuy
ivjhczpokexdtwglfamqprbnuy
ivjhczdokexltwgfgamcprbnuy
ikjhczdokexltwgsfamqirbnux
ivjhczdopjxltwgsfamqprbnny
ivchczdokexltwgniamqprbnuy
ivjhczdooeqltwgsfamqprbniy
ivjhcldonexltwgbfamqprbnuy
ixjhczdokehltwgsfamqprbnuf
ivjhczdckefltwgsfamqppbnuy
ivjhczdoqrxltwgsfamqprbnun
ivjhczdokcxltwgmfarqprbnuy
ivjhcziorexltqgsfamqprbnuy
ivjhwzdokexltwgnfamqprbcuy
ivjhczdoqexltwgsfazqprunuy
iijhczdokexltwgsyamqprbnug
ivjhczdokexltwgxfamhprbnry
ivjhczdakexltwgsfaeqlrbnuy
ivjhqzdokehltwgsfampprbnuy
ivjhczdokexltwlsfpmyprbnuy
ivjhfzdoktxltwgsfamzprbnuy
ivlhvzdokexltwgsvamqprbnuy
ivjhczdbkexltwgsaamqprfnuy
ivahcedokexltigsfamqprbnuy
cvjhczdokexltwgsfamapibnuy
ivjhczkokbxltwgsfbmqprbnuy
pvjuczdnkexltwgsfamqprbnuy
iyjhczdckexotwgsfamqprbnuy
ivjhzzdokvxltwgsfamqprbnuo
ivjhczdobexltwgsxamqprbnry
ivjhczdokexltwgsfaprprbnub
ivjhczdokexltwgofarqprbkuy
ivjhczdokexltwgbfymqprbnhy
ibjhczdokexltwgsfkmqpvbnuy
ivjhczdzkexlywgsfacqprbnuy
hvdhczdokexltwglfamqprbnuy
ivjhczdokexrtwgsfamqprbsuh
ivjhczhokexltngsfamqpjbnuy
ivjhcsjokexltwgsfaeqprbnuy
ivjmczdokexltmgsfamqpbbnuy
wvjhczdokexltwgsfamkpkbnuy
icjhpzdoaexltwgsfamqprbnuy
ivjmczdhkexltwgsfzmqprbnuy
ivjhczdokexytwgsfamqprbwug
ikjhczdjkexljwgsfamqprbnuy
ivjvcdmokexltwgsfamqprbnuy
ivjhazdorixltwgsfamqprbnuy
ivchczdokexltwgsfamzprenuy
ivjcczdokexlttgsfamqpmbnuy
ibchgzdokexltwgsfamqprbnuy
ivjhczdokepltwgsfamqpeenuy
ivjnwzdokexlrwgsfamqprbnuy
ivjhczdokexitwgsfadqlrbnuy
icjhcrdokexltwgsfamqkrbnuy
ivngczdokexltwgsfamqprbyuy
ivjhuudokexlvwgsfamqprbnuy
ivjhczdnkexltwgsfhmqpxbnuy
itjhczdokexltwvsfamgprbnuy
ivjhcddokexltwgsfakqprbnny
ivjhuzdojexltwfsfamqprbnuy
idjhczdokexltwgsfamqukbnuy
ivjhczdokexlzigsfamqprbngy
ivjwczdokexltwgufamqprbnuo
iijhczdokexltwfsfadqprbnuy
ivjhczdukexdtwgsfamqpsbnuy
idjhczdokexllwgssamqprbnuy
zvjhczdokexrtwgsfamqplbnuy
ivphczdofexltwgefamqprbnuy
ivhhczdokexlpwgsjamqprbnuy
ivjhczdovexltwgsfamqprhnuj
ivjhczdoklxltwgseamqprlnuy
ivjhcqdokexltngsfamqprdnuy
ivjhczdoifxltagsfamqprbnuy
izjhczdokexltwjsramqprbnuy
psjhczdokexlgwgsfamqprbnuy
ivjhcadokexltwgsfsmqwrbnuy
ivjhczdokexltwgsfawqiibnuy
ivjhczkokexhtwgsfamqprbnuk
ivjhcmdukexltwgsfamvprbnuy
ivjlczdokexltwgsfamquibnuy
ivjhczdokexntwgyfamqprbniy
ivjhczdokexltwlsfafqprbnuc
ivjhczdosexltrtsfamqprbnuy
ivjhcznokexbtwgsfafqprbnuy
ivwtczdotexltwgsfamqprbnuy
ivjhvzdokexltigsoamqprbnuy
ivjhcmdokexltwasfamqirbnuy
ivthczdokexltwgsfaydprbnuy
ivjhwzdskexltwgsfamqprbnus
icjhczdosuxltwgsfamqprbnuy
ivjhczdokexltwgstamqbrmnuy
iejhczuoktxltwgsfamqprbnuy
ivjhczdokeqltwgskamqprbniy
ivjhlzdokexltugsfamqprbpuy
iwjqczdckexltwgsfamqprbnuy
ivjhwzdokexluwgsfxmqprbnuy
ivjhczdokexltwgwfwmqprbguy
gvjhczkokexltwgsfgmqprbnuy
ivjhczdoyexlhwgsfamqprbnoy
cvjhczdokexltwgsfomqprinuy
vvmhczdokexltwgsfamqprbnun
vvjhczdokexltwgsftmfprbnuy
ivkhckdokhxltwgsfamqprbnuy
iyjhczdkkexltjgsfamqprbnuy
ivlhczdokexltwgsfamqyrbhuy
tvjhmzdokexltwgsfamqorbnuy
ivjhczdokexltwvsfamqprbnxi
ivjhczdowexltwgswamqerbnuy
wvjiczdomexltwgsfamqprbnuy
ivjpizdokexltwgvfamqprbnuy
ivjhuzdokexlzwgspamqprbnuy
ivjhczdokeyltwgkfamqprdnuy
jvjhczdokexlnwgsfamqirbnuy
ivjheidokexltwvsfamqprbnuy
mvjhczdokexltwgsfamqyrsnuy
ivjhazdykexltwgsramqprbnuy
ivjkcodokexltwgsxamqprbnuy
ikjhczdoktxltwgpfamqprbnuy
ivjhyzdfkexmtwgsfamqprbnuy
ivohczdokexltugsfamqprynuy
ivjkczdqkexltwgshamqprbnuy
ivjhczdokexltwgskamqynbnuy
icjhczdokexltwgofamrprbnuy
ivjhlzdokealtwgsfamqsrbnuy
ivehczdybexltwgsfamqprbnuy
ovjhczdokexltwgsfamqirbnuo
ivjoczdokexltwgsfamqurbnty
ivjmczdokexltwgsfrmqprnnuy
ivjhczdowpxltwgbfamqprbnuy
ivjhczdokexltwfsfamqkrgnuy
ivjhwzdokexltwgsfavqprbnuq
jvjhczdokexltwgsiamqprbnny
ivjhlzdouexltwfsfamqprbnuy
ivjhczdokexltwgsfamqbrbnlv
iwjhczdokexltwgsfapqprbnqy
idjhczdokexltwgsaamqrrbnuy
ivjhjzdopepltwgsfamqprbnuy
ivjmczdokejltwgsfamqpbbnuy
ivjhczdokexltwgsuamdprvnuy
injhczdokexltwgefamqurbnuy
iujhczdokexltwgsaamqjrbnuy
ivjhczdokexltwgvfaaqprbnly
ivehczdokexltwgsfamqppbnui
ivxhczdodexltwgsfamqplbnuy
ivjhczfokexltwgsfamqpwbauy
ivjhcztwkexhtwgsfamqprbnuy
ivjeczdokexltygsfmmqprbnuy
ivjhchdokexltwgsmameprbnuy
ivkhczdoklxltwggfamqprbnuy
ivjhczdzkexltwhsfamqprjnuy
ivjhcedokeultngsfamqprbnuy
ivjhczdokexvtwgseabqprbnuy
ivjhczdooexltlgsfamqpibnuy
ivjgczvosexltwgsfamqprbnuy
ivlhczwokexltwgsfamqmrbnuy
lvjhczdokexutwgsfamrprbnuy
ivahczdokexpdwgsfamqprbnuy
ivjhcznokexltwhsfamqpnbnuy
ivjhczdpkyxltwgbfamqprbnuy
ivjhnzdokexltwgsftmqprinuy
ivihczdokexltnhsfamqprbnuy
ivjhcbdokevltwgsfamqprbauy
hgjoczdokexltwgsfamqprbnuy
dvjhczdckexltwgsfamqpybnuy
ivjhcadokesltwgsfsmqwrbnuy
ivjhwzdokexlttgsfamqprbney
ivjhcidokexltwgofamqfrbnuy
ivokwzdokexltwgsfamqprbnuy
ivjiczdokexltwgsfaqqarbnuy
ivjhczdokexqtwfsfamgprbnuy
ivjhczdokealtwgsfamqerbnqy
ivjhczdskexltwgsfamqprznuu
ivjhwzdokexltwjsfdmqprbnuy
ivjhczaokexlzwgsfamqprbnus
ivjhczdokexltwosfamqnrbnux
ivjhczdokexlqwgsfamwprcnuy
ivjhczdqkexltwgswamqpcbnuy
ijjhczdokexnttgsfamqprbnuy
ivjhcedckexltwgsfamqprbnpy
ivjhczdokeyltwgsfamqshbnuy
ivjhczdokexltsgsfamqpmznuy
ivjlczdtkeiltwgsfamqprbnuy
ivjhczdokexltwgsfkmtprbnby
ivjhnzdozexltwgsfamqprbnuc
xqjxczdokexltwgsfamqprbnuy
ivjhczdokeyltwgsfamqnrbnuw
ivjwczgokexltwgsfamvprbnuy
"""





extension StringProtocol {
    func frequencies() -> [Character: Int] {
        return self.reduce(into: [:]) { $0[$1, default: 0] += 1 }
    }
    
    func differences(from other: Self) -> Int {
        return zip(self, other).filter { $0.0 != $0.1 }.count
    }
}

print(input.count)
let ids = input.split(separator: "\n")

let f = ids.first!
print(f.frequencies())
let fr = f.frequencies()
print(fr.contains { $0.value == 2 })
let frs = ids.map { $0.frequencies() }
print(frs.filter{ fr in fr.contains { $0.value == 2} }.count)
print(frs.filter{ fr in fr.contains { $0.value == 3} }.count)
print(247*31)

let z = zip(ids[0], ids[2])

loops:
for i in 0..<ids.count {
    for j in (i+1)..<ids.count {
        let diff = ids[i].differences(from: ids[j])
        if diff == 1 {
            print(ids[i], ids[j], "difference: \(diff)")
            break loops
        }
    }
}


//: [Next](@next)
